name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYWFiNjZhNGYtNzAyMC00NTgyLTgwZmUtZGJjNGZlM2I3MWYzIiwidGVuYW50X2lkIjoiMTMzMmNiYzM5NzE2OTA5ZjVkYWNjM2RmM2VhODU3YTY1NTlkM2E3Mzk2ZTJhMmMyODY2NmI2MjZlNjE5OWQ0OSIsImludGVybmFsX3NlY3JldCI6IjRlMWI2YmJmLTU5OTItNDExYy1hMmI0LTg4NWNkZTBlMDAxMiJ9.NOIGRRZy8pNwirQg8TQ-vAOHxXkIlN8cM1W4fKni9kY"
JWT_SECRET = "asdasdasd"
